name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: Spillgebees/Blazor.Docs.Sdk/.github/workflows/deploy-docs.yml@main
    with:
      docs-project-path: src/Spillgebees.Blazor.Map.Docs/Spillgebees.Blazor.Map.Docs.csproj
      base-href: /Blazor.Map/
